=== j-mackenney/Hotel-Assignment/web/WEB-INF/users.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.uts.edu.au/31284/wsd-diary"
 xmlns="http://www.uts.edu.au/31284/wsd-diary"
 elementFormDefault="qualified">
    
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" minOccurs="1" maxOccurs="unbounded" type="userType">
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="userType">
        <xs:sequence>
            <xs:element name="username" type="xs:string"></xs:element>
            <xs:element name="email" type="emailType"></xs:element>
            <xs:element name="name" type="nameType"></xs:element>
            <xs:element name="password" type="xs:string"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Z]|[a-z]|\.|_)+@([a-z]|-)+\.(([a-z]|-)+\.?){1,}[^\.]"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="nameType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{1}[a-z]+\s[A-Z]{1}[a-z]+"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== j-mackenney/Hotel-Assignment/web/WEB-INF/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="users.xsl"?>
<!--
 xmlns="http://www.uts.edu.au/31284/wsd-diary"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.uts.edu.au/31284/wsd-diary listings.xsd"
 -->
<users xmlns="http://www.uts.edu.au/31284/wsd-diary"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.uts.edu.au/31284/wsd-diary users.xsd">
    <user>
        <username>Ryan117</username>
        <email>ryan@ryanheise.com</email>
        <name>Ryan Heise</name>
        <password>blahblah</password>
    </user>
    <user>
        <username>Ryan118</username>
        <email>ryan@bloggs.com</email>
        <name>Ryan Bloggs</name>
        <password>foobar</password>
    </user>
</users>
